################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../symcipher/aes_big_cbcdec.c \
../symcipher/aes_big_cbcenc.c \
../symcipher/aes_big_ctr.c \
../symcipher/aes_big_ctrcbc.c \
../symcipher/aes_big_dec.c \
../symcipher/aes_big_enc.c \
../symcipher/aes_common.c \
../symcipher/aes_ct.c \
../symcipher/aes_ct64.c \
../symcipher/aes_ct64_cbcdec.c \
../symcipher/aes_ct64_cbcenc.c \
../symcipher/aes_ct64_ctr.c \
../symcipher/aes_ct64_ctrcbc.c \
../symcipher/aes_ct64_dec.c \
../symcipher/aes_ct64_enc.c \
../symcipher/aes_ct_cbcdec.c \
../symcipher/aes_ct_cbcenc.c \
../symcipher/aes_ct_ctr.c \
../symcipher/aes_ct_ctrcbc.c \
../symcipher/aes_ct_dec.c \
../symcipher/aes_ct_enc.c \
../symcipher/aes_pwr8.c \
../symcipher/aes_pwr8_cbcdec.c \
../symcipher/aes_pwr8_cbcenc.c \
../symcipher/aes_pwr8_ctr.c \
../symcipher/aes_pwr8_ctrcbc.c \
../symcipher/aes_small_cbcdec.c \
../symcipher/aes_small_cbcenc.c \
../symcipher/aes_small_ctr.c \
../symcipher/aes_small_ctrcbc.c \
../symcipher/aes_small_dec.c \
../symcipher/aes_small_enc.c \
../symcipher/aes_x86ni.c \
../symcipher/aes_x86ni_cbcdec.c \
../symcipher/aes_x86ni_cbcenc.c \
../symcipher/aes_x86ni_ctr.c \
../symcipher/aes_x86ni_ctrcbc.c \
../symcipher/chacha20_ct.c \
../symcipher/chacha20_sse2.c \
../symcipher/des_ct.c \
../symcipher/des_ct_cbcdec.c \
../symcipher/des_ct_cbcenc.c \
../symcipher/des_support.c \
../symcipher/des_tab.c \
../symcipher/des_tab_cbcdec.c \
../symcipher/des_tab_cbcenc.c \
../symcipher/poly1305_ctmul.c \
../symcipher/poly1305_ctmul32.c \
../symcipher/poly1305_ctmulq.c \
../symcipher/poly1305_i15.c 

C_DEPS += \
./symcipher/aes_big_cbcdec.d \
./symcipher/aes_big_cbcenc.d \
./symcipher/aes_big_ctr.d \
./symcipher/aes_big_ctrcbc.d \
./symcipher/aes_big_dec.d \
./symcipher/aes_big_enc.d \
./symcipher/aes_common.d \
./symcipher/aes_ct.d \
./symcipher/aes_ct64.d \
./symcipher/aes_ct64_cbcdec.d \
./symcipher/aes_ct64_cbcenc.d \
./symcipher/aes_ct64_ctr.d \
./symcipher/aes_ct64_ctrcbc.d \
./symcipher/aes_ct64_dec.d \
./symcipher/aes_ct64_enc.d \
./symcipher/aes_ct_cbcdec.d \
./symcipher/aes_ct_cbcenc.d \
./symcipher/aes_ct_ctr.d \
./symcipher/aes_ct_ctrcbc.d \
./symcipher/aes_ct_dec.d \
./symcipher/aes_ct_enc.d \
./symcipher/aes_pwr8.d \
./symcipher/aes_pwr8_cbcdec.d \
./symcipher/aes_pwr8_cbcenc.d \
./symcipher/aes_pwr8_ctr.d \
./symcipher/aes_pwr8_ctrcbc.d \
./symcipher/aes_small_cbcdec.d \
./symcipher/aes_small_cbcenc.d \
./symcipher/aes_small_ctr.d \
./symcipher/aes_small_ctrcbc.d \
./symcipher/aes_small_dec.d \
./symcipher/aes_small_enc.d \
./symcipher/aes_x86ni.d \
./symcipher/aes_x86ni_cbcdec.d \
./symcipher/aes_x86ni_cbcenc.d \
./symcipher/aes_x86ni_ctr.d \
./symcipher/aes_x86ni_ctrcbc.d \
./symcipher/chacha20_ct.d \
./symcipher/chacha20_sse2.d \
./symcipher/des_ct.d \
./symcipher/des_ct_cbcdec.d \
./symcipher/des_ct_cbcenc.d \
./symcipher/des_support.d \
./symcipher/des_tab.d \
./symcipher/des_tab_cbcdec.d \
./symcipher/des_tab_cbcenc.d \
./symcipher/poly1305_ctmul.d \
./symcipher/poly1305_ctmul32.d \
./symcipher/poly1305_ctmulq.d \
./symcipher/poly1305_i15.d 

OBJS += \
./symcipher/aes_big_cbcdec.obj \
./symcipher/aes_big_cbcenc.obj \
./symcipher/aes_big_ctr.obj \
./symcipher/aes_big_ctrcbc.obj \
./symcipher/aes_big_dec.obj \
./symcipher/aes_big_enc.obj \
./symcipher/aes_common.obj \
./symcipher/aes_ct.obj \
./symcipher/aes_ct64.obj \
./symcipher/aes_ct64_cbcdec.obj \
./symcipher/aes_ct64_cbcenc.obj \
./symcipher/aes_ct64_ctr.obj \
./symcipher/aes_ct64_ctrcbc.obj \
./symcipher/aes_ct64_dec.obj \
./symcipher/aes_ct64_enc.obj \
./symcipher/aes_ct_cbcdec.obj \
./symcipher/aes_ct_cbcenc.obj \
./symcipher/aes_ct_ctr.obj \
./symcipher/aes_ct_ctrcbc.obj \
./symcipher/aes_ct_dec.obj \
./symcipher/aes_ct_enc.obj \
./symcipher/aes_pwr8.obj \
./symcipher/aes_pwr8_cbcdec.obj \
./symcipher/aes_pwr8_cbcenc.obj \
./symcipher/aes_pwr8_ctr.obj \
./symcipher/aes_pwr8_ctrcbc.obj \
./symcipher/aes_small_cbcdec.obj \
./symcipher/aes_small_cbcenc.obj \
./symcipher/aes_small_ctr.obj \
./symcipher/aes_small_ctrcbc.obj \
./symcipher/aes_small_dec.obj \
./symcipher/aes_small_enc.obj \
./symcipher/aes_x86ni.obj \
./symcipher/aes_x86ni_cbcdec.obj \
./symcipher/aes_x86ni_cbcenc.obj \
./symcipher/aes_x86ni_ctr.obj \
./symcipher/aes_x86ni_ctrcbc.obj \
./symcipher/chacha20_ct.obj \
./symcipher/chacha20_sse2.obj \
./symcipher/des_ct.obj \
./symcipher/des_ct_cbcdec.obj \
./symcipher/des_ct_cbcenc.obj \
./symcipher/des_support.obj \
./symcipher/des_tab.obj \
./symcipher/des_tab_cbcdec.obj \
./symcipher/des_tab_cbcenc.obj \
./symcipher/poly1305_ctmul.obj \
./symcipher/poly1305_ctmul32.obj \
./symcipher/poly1305_ctmulq.obj \
./symcipher/poly1305_i15.obj 

OBJS__QUOTED += \
"symcipher/aes_big_cbcdec.obj" \
"symcipher/aes_big_cbcenc.obj" \
"symcipher/aes_big_ctr.obj" \
"symcipher/aes_big_ctrcbc.obj" \
"symcipher/aes_big_dec.obj" \
"symcipher/aes_big_enc.obj" \
"symcipher/aes_common.obj" \
"symcipher/aes_ct.obj" \
"symcipher/aes_ct64.obj" \
"symcipher/aes_ct64_cbcdec.obj" \
"symcipher/aes_ct64_cbcenc.obj" \
"symcipher/aes_ct64_ctr.obj" \
"symcipher/aes_ct64_ctrcbc.obj" \
"symcipher/aes_ct64_dec.obj" \
"symcipher/aes_ct64_enc.obj" \
"symcipher/aes_ct_cbcdec.obj" \
"symcipher/aes_ct_cbcenc.obj" \
"symcipher/aes_ct_ctr.obj" \
"symcipher/aes_ct_ctrcbc.obj" \
"symcipher/aes_ct_dec.obj" \
"symcipher/aes_ct_enc.obj" \
"symcipher/aes_pwr8.obj" \
"symcipher/aes_pwr8_cbcdec.obj" \
"symcipher/aes_pwr8_cbcenc.obj" \
"symcipher/aes_pwr8_ctr.obj" \
"symcipher/aes_pwr8_ctrcbc.obj" \
"symcipher/aes_small_cbcdec.obj" \
"symcipher/aes_small_cbcenc.obj" \
"symcipher/aes_small_ctr.obj" \
"symcipher/aes_small_ctrcbc.obj" \
"symcipher/aes_small_dec.obj" \
"symcipher/aes_small_enc.obj" \
"symcipher/aes_x86ni.obj" \
"symcipher/aes_x86ni_cbcdec.obj" \
"symcipher/aes_x86ni_cbcenc.obj" \
"symcipher/aes_x86ni_ctr.obj" \
"symcipher/aes_x86ni_ctrcbc.obj" \
"symcipher/chacha20_ct.obj" \
"symcipher/chacha20_sse2.obj" \
"symcipher/des_ct.obj" \
"symcipher/des_ct_cbcdec.obj" \
"symcipher/des_ct_cbcenc.obj" \
"symcipher/des_support.obj" \
"symcipher/des_tab.obj" \
"symcipher/des_tab_cbcdec.obj" \
"symcipher/des_tab_cbcenc.obj" \
"symcipher/poly1305_ctmul.obj" \
"symcipher/poly1305_ctmul32.obj" \
"symcipher/poly1305_ctmulq.obj" \
"symcipher/poly1305_i15.obj" 

C_DEPS__QUOTED += \
"symcipher/aes_big_cbcdec.d" \
"symcipher/aes_big_cbcenc.d" \
"symcipher/aes_big_ctr.d" \
"symcipher/aes_big_ctrcbc.d" \
"symcipher/aes_big_dec.d" \
"symcipher/aes_big_enc.d" \
"symcipher/aes_common.d" \
"symcipher/aes_ct.d" \
"symcipher/aes_ct64.d" \
"symcipher/aes_ct64_cbcdec.d" \
"symcipher/aes_ct64_cbcenc.d" \
"symcipher/aes_ct64_ctr.d" \
"symcipher/aes_ct64_ctrcbc.d" \
"symcipher/aes_ct64_dec.d" \
"symcipher/aes_ct64_enc.d" \
"symcipher/aes_ct_cbcdec.d" \
"symcipher/aes_ct_cbcenc.d" \
"symcipher/aes_ct_ctr.d" \
"symcipher/aes_ct_ctrcbc.d" \
"symcipher/aes_ct_dec.d" \
"symcipher/aes_ct_enc.d" \
"symcipher/aes_pwr8.d" \
"symcipher/aes_pwr8_cbcdec.d" \
"symcipher/aes_pwr8_cbcenc.d" \
"symcipher/aes_pwr8_ctr.d" \
"symcipher/aes_pwr8_ctrcbc.d" \
"symcipher/aes_small_cbcdec.d" \
"symcipher/aes_small_cbcenc.d" \
"symcipher/aes_small_ctr.d" \
"symcipher/aes_small_ctrcbc.d" \
"symcipher/aes_small_dec.d" \
"symcipher/aes_small_enc.d" \
"symcipher/aes_x86ni.d" \
"symcipher/aes_x86ni_cbcdec.d" \
"symcipher/aes_x86ni_cbcenc.d" \
"symcipher/aes_x86ni_ctr.d" \
"symcipher/aes_x86ni_ctrcbc.d" \
"symcipher/chacha20_ct.d" \
"symcipher/chacha20_sse2.d" \
"symcipher/des_ct.d" \
"symcipher/des_ct_cbcdec.d" \
"symcipher/des_ct_cbcenc.d" \
"symcipher/des_support.d" \
"symcipher/des_tab.d" \
"symcipher/des_tab_cbcdec.d" \
"symcipher/des_tab_cbcenc.d" \
"symcipher/poly1305_ctmul.d" \
"symcipher/poly1305_ctmul32.d" \
"symcipher/poly1305_ctmulq.d" \
"symcipher/poly1305_i15.d" 

C_SRCS__QUOTED += \
"../symcipher/aes_big_cbcdec.c" \
"../symcipher/aes_big_cbcenc.c" \
"../symcipher/aes_big_ctr.c" \
"../symcipher/aes_big_ctrcbc.c" \
"../symcipher/aes_big_dec.c" \
"../symcipher/aes_big_enc.c" \
"../symcipher/aes_common.c" \
"../symcipher/aes_ct.c" \
"../symcipher/aes_ct64.c" \
"../symcipher/aes_ct64_cbcdec.c" \
"../symcipher/aes_ct64_cbcenc.c" \
"../symcipher/aes_ct64_ctr.c" \
"../symcipher/aes_ct64_ctrcbc.c" \
"../symcipher/aes_ct64_dec.c" \
"../symcipher/aes_ct64_enc.c" \
"../symcipher/aes_ct_cbcdec.c" \
"../symcipher/aes_ct_cbcenc.c" \
"../symcipher/aes_ct_ctr.c" \
"../symcipher/aes_ct_ctrcbc.c" \
"../symcipher/aes_ct_dec.c" \
"../symcipher/aes_ct_enc.c" \
"../symcipher/aes_pwr8.c" \
"../symcipher/aes_pwr8_cbcdec.c" \
"../symcipher/aes_pwr8_cbcenc.c" \
"../symcipher/aes_pwr8_ctr.c" \
"../symcipher/aes_pwr8_ctrcbc.c" \
"../symcipher/aes_small_cbcdec.c" \
"../symcipher/aes_small_cbcenc.c" \
"../symcipher/aes_small_ctr.c" \
"../symcipher/aes_small_ctrcbc.c" \
"../symcipher/aes_small_dec.c" \
"../symcipher/aes_small_enc.c" \
"../symcipher/aes_x86ni.c" \
"../symcipher/aes_x86ni_cbcdec.c" \
"../symcipher/aes_x86ni_cbcenc.c" \
"../symcipher/aes_x86ni_ctr.c" \
"../symcipher/aes_x86ni_ctrcbc.c" \
"../symcipher/chacha20_ct.c" \
"../symcipher/chacha20_sse2.c" \
"../symcipher/des_ct.c" \
"../symcipher/des_ct_cbcdec.c" \
"../symcipher/des_ct_cbcenc.c" \
"../symcipher/des_support.c" \
"../symcipher/des_tab.c" \
"../symcipher/des_tab_cbcdec.c" \
"../symcipher/des_tab_cbcenc.c" \
"../symcipher/poly1305_ctmul.c" \
"../symcipher/poly1305_ctmul32.c" \
"../symcipher/poly1305_ctmulq.c" \
"../symcipher/poly1305_i15.c" 


