################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ssl/prf.c \
../ssl/prf_md5sha1.c \
../ssl/prf_sha256.c \
../ssl/prf_sha384.c \
../ssl/ssl_ccert_single_ec.c \
../ssl/ssl_ccert_single_rsa.c \
../ssl/ssl_client.c \
../ssl/ssl_client_default_rsapub.c \
../ssl/ssl_client_full.c \
../ssl/ssl_engine.c \
../ssl/ssl_engine_default_aescbc.c \
../ssl/ssl_engine_default_aesccm.c \
../ssl/ssl_engine_default_aesgcm.c \
../ssl/ssl_engine_default_chapol.c \
../ssl/ssl_engine_default_descbc.c \
../ssl/ssl_engine_default_ec.c \
../ssl/ssl_engine_default_ecdsa.c \
../ssl/ssl_engine_default_rsavrfy.c \
../ssl/ssl_hashes.c \
../ssl/ssl_hs_client.c \
../ssl/ssl_hs_server.c \
../ssl/ssl_io.c \
../ssl/ssl_keyexport.c \
../ssl/ssl_lru.c \
../ssl/ssl_rec_cbc.c \
../ssl/ssl_rec_ccm.c \
../ssl/ssl_rec_chapol.c \
../ssl/ssl_rec_gcm.c \
../ssl/ssl_scert_single_ec.c \
../ssl/ssl_scert_single_rsa.c \
../ssl/ssl_server.c \
../ssl/ssl_server_full_ec.c \
../ssl/ssl_server_full_rsa.c \
../ssl/ssl_server_mine2c.c \
../ssl/ssl_server_mine2g.c \
../ssl/ssl_server_minf2c.c \
../ssl/ssl_server_minf2g.c \
../ssl/ssl_server_minr2g.c \
../ssl/ssl_server_minu2g.c \
../ssl/ssl_server_minv2g.c 

C_DEPS += \
./ssl/prf.d \
./ssl/prf_md5sha1.d \
./ssl/prf_sha256.d \
./ssl/prf_sha384.d \
./ssl/ssl_ccert_single_ec.d \
./ssl/ssl_ccert_single_rsa.d \
./ssl/ssl_client.d \
./ssl/ssl_client_default_rsapub.d \
./ssl/ssl_client_full.d \
./ssl/ssl_engine.d \
./ssl/ssl_engine_default_aescbc.d \
./ssl/ssl_engine_default_aesccm.d \
./ssl/ssl_engine_default_aesgcm.d \
./ssl/ssl_engine_default_chapol.d \
./ssl/ssl_engine_default_descbc.d \
./ssl/ssl_engine_default_ec.d \
./ssl/ssl_engine_default_ecdsa.d \
./ssl/ssl_engine_default_rsavrfy.d \
./ssl/ssl_hashes.d \
./ssl/ssl_hs_client.d \
./ssl/ssl_hs_server.d \
./ssl/ssl_io.d \
./ssl/ssl_keyexport.d \
./ssl/ssl_lru.d \
./ssl/ssl_rec_cbc.d \
./ssl/ssl_rec_ccm.d \
./ssl/ssl_rec_chapol.d \
./ssl/ssl_rec_gcm.d \
./ssl/ssl_scert_single_ec.d \
./ssl/ssl_scert_single_rsa.d \
./ssl/ssl_server.d \
./ssl/ssl_server_full_ec.d \
./ssl/ssl_server_full_rsa.d \
./ssl/ssl_server_mine2c.d \
./ssl/ssl_server_mine2g.d \
./ssl/ssl_server_minf2c.d \
./ssl/ssl_server_minf2g.d \
./ssl/ssl_server_minr2g.d \
./ssl/ssl_server_minu2g.d \
./ssl/ssl_server_minv2g.d 

OBJS += \
./ssl/prf.obj \
./ssl/prf_md5sha1.obj \
./ssl/prf_sha256.obj \
./ssl/prf_sha384.obj \
./ssl/ssl_ccert_single_ec.obj \
./ssl/ssl_ccert_single_rsa.obj \
./ssl/ssl_client.obj \
./ssl/ssl_client_default_rsapub.obj \
./ssl/ssl_client_full.obj \
./ssl/ssl_engine.obj \
./ssl/ssl_engine_default_aescbc.obj \
./ssl/ssl_engine_default_aesccm.obj \
./ssl/ssl_engine_default_aesgcm.obj \
./ssl/ssl_engine_default_chapol.obj \
./ssl/ssl_engine_default_descbc.obj \
./ssl/ssl_engine_default_ec.obj \
./ssl/ssl_engine_default_ecdsa.obj \
./ssl/ssl_engine_default_rsavrfy.obj \
./ssl/ssl_hashes.obj \
./ssl/ssl_hs_client.obj \
./ssl/ssl_hs_server.obj \
./ssl/ssl_io.obj \
./ssl/ssl_keyexport.obj \
./ssl/ssl_lru.obj \
./ssl/ssl_rec_cbc.obj \
./ssl/ssl_rec_ccm.obj \
./ssl/ssl_rec_chapol.obj \
./ssl/ssl_rec_gcm.obj \
./ssl/ssl_scert_single_ec.obj \
./ssl/ssl_scert_single_rsa.obj \
./ssl/ssl_server.obj \
./ssl/ssl_server_full_ec.obj \
./ssl/ssl_server_full_rsa.obj \
./ssl/ssl_server_mine2c.obj \
./ssl/ssl_server_mine2g.obj \
./ssl/ssl_server_minf2c.obj \
./ssl/ssl_server_minf2g.obj \
./ssl/ssl_server_minr2g.obj \
./ssl/ssl_server_minu2g.obj \
./ssl/ssl_server_minv2g.obj 

OBJS__QUOTED += \
"ssl/prf.obj" \
"ssl/prf_md5sha1.obj" \
"ssl/prf_sha256.obj" \
"ssl/prf_sha384.obj" \
"ssl/ssl_ccert_single_ec.obj" \
"ssl/ssl_ccert_single_rsa.obj" \
"ssl/ssl_client.obj" \
"ssl/ssl_client_default_rsapub.obj" \
"ssl/ssl_client_full.obj" \
"ssl/ssl_engine.obj" \
"ssl/ssl_engine_default_aescbc.obj" \
"ssl/ssl_engine_default_aesccm.obj" \
"ssl/ssl_engine_default_aesgcm.obj" \
"ssl/ssl_engine_default_chapol.obj" \
"ssl/ssl_engine_default_descbc.obj" \
"ssl/ssl_engine_default_ec.obj" \
"ssl/ssl_engine_default_ecdsa.obj" \
"ssl/ssl_engine_default_rsavrfy.obj" \
"ssl/ssl_hashes.obj" \
"ssl/ssl_hs_client.obj" \
"ssl/ssl_hs_server.obj" \
"ssl/ssl_io.obj" \
"ssl/ssl_keyexport.obj" \
"ssl/ssl_lru.obj" \
"ssl/ssl_rec_cbc.obj" \
"ssl/ssl_rec_ccm.obj" \
"ssl/ssl_rec_chapol.obj" \
"ssl/ssl_rec_gcm.obj" \
"ssl/ssl_scert_single_ec.obj" \
"ssl/ssl_scert_single_rsa.obj" \
"ssl/ssl_server.obj" \
"ssl/ssl_server_full_ec.obj" \
"ssl/ssl_server_full_rsa.obj" \
"ssl/ssl_server_mine2c.obj" \
"ssl/ssl_server_mine2g.obj" \
"ssl/ssl_server_minf2c.obj" \
"ssl/ssl_server_minf2g.obj" \
"ssl/ssl_server_minr2g.obj" \
"ssl/ssl_server_minu2g.obj" \
"ssl/ssl_server_minv2g.obj" 

C_DEPS__QUOTED += \
"ssl/prf.d" \
"ssl/prf_md5sha1.d" \
"ssl/prf_sha256.d" \
"ssl/prf_sha384.d" \
"ssl/ssl_ccert_single_ec.d" \
"ssl/ssl_ccert_single_rsa.d" \
"ssl/ssl_client.d" \
"ssl/ssl_client_default_rsapub.d" \
"ssl/ssl_client_full.d" \
"ssl/ssl_engine.d" \
"ssl/ssl_engine_default_aescbc.d" \
"ssl/ssl_engine_default_aesccm.d" \
"ssl/ssl_engine_default_aesgcm.d" \
"ssl/ssl_engine_default_chapol.d" \
"ssl/ssl_engine_default_descbc.d" \
"ssl/ssl_engine_default_ec.d" \
"ssl/ssl_engine_default_ecdsa.d" \
"ssl/ssl_engine_default_rsavrfy.d" \
"ssl/ssl_hashes.d" \
"ssl/ssl_hs_client.d" \
"ssl/ssl_hs_server.d" \
"ssl/ssl_io.d" \
"ssl/ssl_keyexport.d" \
"ssl/ssl_lru.d" \
"ssl/ssl_rec_cbc.d" \
"ssl/ssl_rec_ccm.d" \
"ssl/ssl_rec_chapol.d" \
"ssl/ssl_rec_gcm.d" \
"ssl/ssl_scert_single_ec.d" \
"ssl/ssl_scert_single_rsa.d" \
"ssl/ssl_server.d" \
"ssl/ssl_server_full_ec.d" \
"ssl/ssl_server_full_rsa.d" \
"ssl/ssl_server_mine2c.d" \
"ssl/ssl_server_mine2g.d" \
"ssl/ssl_server_minf2c.d" \
"ssl/ssl_server_minf2g.d" \
"ssl/ssl_server_minr2g.d" \
"ssl/ssl_server_minu2g.d" \
"ssl/ssl_server_minv2g.d" 

C_SRCS__QUOTED += \
"../ssl/prf.c" \
"../ssl/prf_md5sha1.c" \
"../ssl/prf_sha256.c" \
"../ssl/prf_sha384.c" \
"../ssl/ssl_ccert_single_ec.c" \
"../ssl/ssl_ccert_single_rsa.c" \
"../ssl/ssl_client.c" \
"../ssl/ssl_client_default_rsapub.c" \
"../ssl/ssl_client_full.c" \
"../ssl/ssl_engine.c" \
"../ssl/ssl_engine_default_aescbc.c" \
"../ssl/ssl_engine_default_aesccm.c" \
"../ssl/ssl_engine_default_aesgcm.c" \
"../ssl/ssl_engine_default_chapol.c" \
"../ssl/ssl_engine_default_descbc.c" \
"../ssl/ssl_engine_default_ec.c" \
"../ssl/ssl_engine_default_ecdsa.c" \
"../ssl/ssl_engine_default_rsavrfy.c" \
"../ssl/ssl_hashes.c" \
"../ssl/ssl_hs_client.c" \
"../ssl/ssl_hs_server.c" \
"../ssl/ssl_io.c" \
"../ssl/ssl_keyexport.c" \
"../ssl/ssl_lru.c" \
"../ssl/ssl_rec_cbc.c" \
"../ssl/ssl_rec_ccm.c" \
"../ssl/ssl_rec_chapol.c" \
"../ssl/ssl_rec_gcm.c" \
"../ssl/ssl_scert_single_ec.c" \
"../ssl/ssl_scert_single_rsa.c" \
"../ssl/ssl_server.c" \
"../ssl/ssl_server_full_ec.c" \
"../ssl/ssl_server_full_rsa.c" \
"../ssl/ssl_server_mine2c.c" \
"../ssl/ssl_server_mine2g.c" \
"../ssl/ssl_server_minf2c.c" \
"../ssl/ssl_server_minf2g.c" \
"../ssl/ssl_server_minr2g.c" \
"../ssl/ssl_server_minu2g.c" \
"../ssl/ssl_server_minv2g.c" 


