################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../int/i15_add.c \
../int/i15_bitlen.c \
../int/i15_decmod.c \
../int/i15_decode.c \
../int/i15_decred.c \
../int/i15_encode.c \
../int/i15_fmont.c \
../int/i15_iszero.c \
../int/i15_moddiv.c \
../int/i15_modpow.c \
../int/i15_modpow2.c \
../int/i15_montmul.c \
../int/i15_mulacc.c \
../int/i15_muladd.c \
../int/i15_ninv15.c \
../int/i15_reduce.c \
../int/i15_rshift.c \
../int/i15_sub.c \
../int/i15_tmont.c \
../int/i31_add.c \
../int/i31_bitlen.c \
../int/i31_decmod.c \
../int/i31_decode.c \
../int/i31_decred.c \
../int/i31_encode.c \
../int/i31_fmont.c \
../int/i31_iszero.c \
../int/i31_moddiv.c \
../int/i31_modpow.c \
../int/i31_modpow2.c \
../int/i31_montmul.c \
../int/i31_mulacc.c \
../int/i31_muladd.c \
../int/i31_ninv31.c \
../int/i31_reduce.c \
../int/i31_rshift.c \
../int/i31_sub.c \
../int/i31_tmont.c \
../int/i32_add.c \
../int/i32_bitlen.c \
../int/i32_decmod.c \
../int/i32_decode.c \
../int/i32_decred.c \
../int/i32_div32.c \
../int/i32_encode.c \
../int/i32_fmont.c \
../int/i32_iszero.c \
../int/i32_modpow.c \
../int/i32_montmul.c \
../int/i32_mulacc.c \
../int/i32_muladd.c \
../int/i32_ninv32.c \
../int/i32_reduce.c \
../int/i32_sub.c \
../int/i32_tmont.c \
../int/i62_modpow2.c 

C_DEPS += \
./int/i15_add.d \
./int/i15_bitlen.d \
./int/i15_decmod.d \
./int/i15_decode.d \
./int/i15_decred.d \
./int/i15_encode.d \
./int/i15_fmont.d \
./int/i15_iszero.d \
./int/i15_moddiv.d \
./int/i15_modpow.d \
./int/i15_modpow2.d \
./int/i15_montmul.d \
./int/i15_mulacc.d \
./int/i15_muladd.d \
./int/i15_ninv15.d \
./int/i15_reduce.d \
./int/i15_rshift.d \
./int/i15_sub.d \
./int/i15_tmont.d \
./int/i31_add.d \
./int/i31_bitlen.d \
./int/i31_decmod.d \
./int/i31_decode.d \
./int/i31_decred.d \
./int/i31_encode.d \
./int/i31_fmont.d \
./int/i31_iszero.d \
./int/i31_moddiv.d \
./int/i31_modpow.d \
./int/i31_modpow2.d \
./int/i31_montmul.d \
./int/i31_mulacc.d \
./int/i31_muladd.d \
./int/i31_ninv31.d \
./int/i31_reduce.d \
./int/i31_rshift.d \
./int/i31_sub.d \
./int/i31_tmont.d \
./int/i32_add.d \
./int/i32_bitlen.d \
./int/i32_decmod.d \
./int/i32_decode.d \
./int/i32_decred.d \
./int/i32_div32.d \
./int/i32_encode.d \
./int/i32_fmont.d \
./int/i32_iszero.d \
./int/i32_modpow.d \
./int/i32_montmul.d \
./int/i32_mulacc.d \
./int/i32_muladd.d \
./int/i32_ninv32.d \
./int/i32_reduce.d \
./int/i32_sub.d \
./int/i32_tmont.d \
./int/i62_modpow2.d 

OBJS += \
./int/i15_add.obj \
./int/i15_bitlen.obj \
./int/i15_decmod.obj \
./int/i15_decode.obj \
./int/i15_decred.obj \
./int/i15_encode.obj \
./int/i15_fmont.obj \
./int/i15_iszero.obj \
./int/i15_moddiv.obj \
./int/i15_modpow.obj \
./int/i15_modpow2.obj \
./int/i15_montmul.obj \
./int/i15_mulacc.obj \
./int/i15_muladd.obj \
./int/i15_ninv15.obj \
./int/i15_reduce.obj \
./int/i15_rshift.obj \
./int/i15_sub.obj \
./int/i15_tmont.obj \
./int/i31_add.obj \
./int/i31_bitlen.obj \
./int/i31_decmod.obj \
./int/i31_decode.obj \
./int/i31_decred.obj \
./int/i31_encode.obj \
./int/i31_fmont.obj \
./int/i31_iszero.obj \
./int/i31_moddiv.obj \
./int/i31_modpow.obj \
./int/i31_modpow2.obj \
./int/i31_montmul.obj \
./int/i31_mulacc.obj \
./int/i31_muladd.obj \
./int/i31_ninv31.obj \
./int/i31_reduce.obj \
./int/i31_rshift.obj \
./int/i31_sub.obj \
./int/i31_tmont.obj \
./int/i32_add.obj \
./int/i32_bitlen.obj \
./int/i32_decmod.obj \
./int/i32_decode.obj \
./int/i32_decred.obj \
./int/i32_div32.obj \
./int/i32_encode.obj \
./int/i32_fmont.obj \
./int/i32_iszero.obj \
./int/i32_modpow.obj \
./int/i32_montmul.obj \
./int/i32_mulacc.obj \
./int/i32_muladd.obj \
./int/i32_ninv32.obj \
./int/i32_reduce.obj \
./int/i32_sub.obj \
./int/i32_tmont.obj \
./int/i62_modpow2.obj 

OBJS__QUOTED += \
"int/i15_add.obj" \
"int/i15_bitlen.obj" \
"int/i15_decmod.obj" \
"int/i15_decode.obj" \
"int/i15_decred.obj" \
"int/i15_encode.obj" \
"int/i15_fmont.obj" \
"int/i15_iszero.obj" \
"int/i15_moddiv.obj" \
"int/i15_modpow.obj" \
"int/i15_modpow2.obj" \
"int/i15_montmul.obj" \
"int/i15_mulacc.obj" \
"int/i15_muladd.obj" \
"int/i15_ninv15.obj" \
"int/i15_reduce.obj" \
"int/i15_rshift.obj" \
"int/i15_sub.obj" \
"int/i15_tmont.obj" \
"int/i31_add.obj" \
"int/i31_bitlen.obj" \
"int/i31_decmod.obj" \
"int/i31_decode.obj" \
"int/i31_decred.obj" \
"int/i31_encode.obj" \
"int/i31_fmont.obj" \
"int/i31_iszero.obj" \
"int/i31_moddiv.obj" \
"int/i31_modpow.obj" \
"int/i31_modpow2.obj" \
"int/i31_montmul.obj" \
"int/i31_mulacc.obj" \
"int/i31_muladd.obj" \
"int/i31_ninv31.obj" \
"int/i31_reduce.obj" \
"int/i31_rshift.obj" \
"int/i31_sub.obj" \
"int/i31_tmont.obj" \
"int/i32_add.obj" \
"int/i32_bitlen.obj" \
"int/i32_decmod.obj" \
"int/i32_decode.obj" \
"int/i32_decred.obj" \
"int/i32_div32.obj" \
"int/i32_encode.obj" \
"int/i32_fmont.obj" \
"int/i32_iszero.obj" \
"int/i32_modpow.obj" \
"int/i32_montmul.obj" \
"int/i32_mulacc.obj" \
"int/i32_muladd.obj" \
"int/i32_ninv32.obj" \
"int/i32_reduce.obj" \
"int/i32_sub.obj" \
"int/i32_tmont.obj" \
"int/i62_modpow2.obj" 

C_DEPS__QUOTED += \
"int/i15_add.d" \
"int/i15_bitlen.d" \
"int/i15_decmod.d" \
"int/i15_decode.d" \
"int/i15_decred.d" \
"int/i15_encode.d" \
"int/i15_fmont.d" \
"int/i15_iszero.d" \
"int/i15_moddiv.d" \
"int/i15_modpow.d" \
"int/i15_modpow2.d" \
"int/i15_montmul.d" \
"int/i15_mulacc.d" \
"int/i15_muladd.d" \
"int/i15_ninv15.d" \
"int/i15_reduce.d" \
"int/i15_rshift.d" \
"int/i15_sub.d" \
"int/i15_tmont.d" \
"int/i31_add.d" \
"int/i31_bitlen.d" \
"int/i31_decmod.d" \
"int/i31_decode.d" \
"int/i31_decred.d" \
"int/i31_encode.d" \
"int/i31_fmont.d" \
"int/i31_iszero.d" \
"int/i31_moddiv.d" \
"int/i31_modpow.d" \
"int/i31_modpow2.d" \
"int/i31_montmul.d" \
"int/i31_mulacc.d" \
"int/i31_muladd.d" \
"int/i31_ninv31.d" \
"int/i31_reduce.d" \
"int/i31_rshift.d" \
"int/i31_sub.d" \
"int/i31_tmont.d" \
"int/i32_add.d" \
"int/i32_bitlen.d" \
"int/i32_decmod.d" \
"int/i32_decode.d" \
"int/i32_decred.d" \
"int/i32_div32.d" \
"int/i32_encode.d" \
"int/i32_fmont.d" \
"int/i32_iszero.d" \
"int/i32_modpow.d" \
"int/i32_montmul.d" \
"int/i32_mulacc.d" \
"int/i32_muladd.d" \
"int/i32_ninv32.d" \
"int/i32_reduce.d" \
"int/i32_sub.d" \
"int/i32_tmont.d" \
"int/i62_modpow2.d" 

C_SRCS__QUOTED += \
"../int/i15_add.c" \
"../int/i15_bitlen.c" \
"../int/i15_decmod.c" \
"../int/i15_decode.c" \
"../int/i15_decred.c" \
"../int/i15_encode.c" \
"../int/i15_fmont.c" \
"../int/i15_iszero.c" \
"../int/i15_moddiv.c" \
"../int/i15_modpow.c" \
"../int/i15_modpow2.c" \
"../int/i15_montmul.c" \
"../int/i15_mulacc.c" \
"../int/i15_muladd.c" \
"../int/i15_ninv15.c" \
"../int/i15_reduce.c" \
"../int/i15_rshift.c" \
"../int/i15_sub.c" \
"../int/i15_tmont.c" \
"../int/i31_add.c" \
"../int/i31_bitlen.c" \
"../int/i31_decmod.c" \
"../int/i31_decode.c" \
"../int/i31_decred.c" \
"../int/i31_encode.c" \
"../int/i31_fmont.c" \
"../int/i31_iszero.c" \
"../int/i31_moddiv.c" \
"../int/i31_modpow.c" \
"../int/i31_modpow2.c" \
"../int/i31_montmul.c" \
"../int/i31_mulacc.c" \
"../int/i31_muladd.c" \
"../int/i31_ninv31.c" \
"../int/i31_reduce.c" \
"../int/i31_rshift.c" \
"../int/i31_sub.c" \
"../int/i31_tmont.c" \
"../int/i32_add.c" \
"../int/i32_bitlen.c" \
"../int/i32_decmod.c" \
"../int/i32_decode.c" \
"../int/i32_decred.c" \
"../int/i32_div32.c" \
"../int/i32_encode.c" \
"../int/i32_fmont.c" \
"../int/i32_iszero.c" \
"../int/i32_modpow.c" \
"../int/i32_montmul.c" \
"../int/i32_mulacc.c" \
"../int/i32_muladd.c" \
"../int/i32_ninv32.c" \
"../int/i32_reduce.c" \
"../int/i32_sub.c" \
"../int/i32_tmont.c" \
"../int/i62_modpow2.c" 


